INSERT INTO CATEGORIA (CAT_NAME) VALUES ('CATEGORIA 1');
INSERT INTO CATEGORIA (CAT_NAME) VALUES ('CATEGORIA 2');
INSERT INTO CATEGORIA (CAT_NAME) VALUES ('CATEGORIA 3');
INSERT INTO CATEGORIA (CAT_NAME) VALUES ('CATEGORIA 4');

INSERT INTO PRODUTO ( PRD_DAT_CADASTRO, PRD_DESC, PRD_NAME, PRD_PRECO, PRD_CATEGORIA ) VALUES (TO_DATE('15/10/2020', 'DD/MM/YYYY'), 'DESCRIÇÃO PRODUTO 1', 'PRODUTO 1', 12, 1);
INSERT INTO PRODUTO ( PRD_DAT_CADASTRO, PRD_DESC, PRD_NAME, PRD_PRECO, PRD_CATEGORIA ) VALUES (TO_DATE('20/03/2020', 'DD/MM/YYYY'), 'DESCRIÇÃO PRODUTO 2', 'PRODUTO 2', 12, 2);
INSERT INTO PRODUTO ( PRD_DAT_CADASTRO, PRD_DESC, PRD_NAME, PRD_PRECO, PRD_CATEGORIA ) VALUES (TO_DATE('11/01/2021', 'DD/MM/YYYY'), 'DESCRIÇÃO PRODUTO 3', 'PRODUTO 3', 12, 3);
INSERT INTO PRODUTO ( PRD_DAT_CADASTRO, PRD_DESC, PRD_NAME, PRD_PRECO, PRD_CATEGORIA ) VALUES (TO_DATE('05/11/2018', 'DD/MM/YYYY'), 'DESCRIÇÃO PRODUTO 4', 'PRODUTO 4', 12, 4);